### ISSUE TITLE
No support for building native libraries on other platforms

### ISSUE THREAD

**Issue by ltning** [jitsi/jitsi-srtp#11]
Trying to piece together how to get jitsi server-side running on FreeBSD, and keep finding native pre-compiled binaries in various of the repositories - this being one of them. Is there a reason these things need native code? If yes, it would be preferable if the build process was at least platform-agnostic. The assumption that everything is Linux isn't entirely true :)

**Comment by JonathanLennox** [comment]
The use of native code is optional; the code will fall back to a pure-Java crypto implementation (using BouncyCastle) if the native library isn't found.  The OpenSSL-based implementation is substantially faster, however, so it's best to use the native code if possible.

The reason the build process needs to be platform-dependent is that platforms are annoyingly inconsistent about things like shared library extensions and the like.

A PR to add FreeBSD support to jitsi-srtp would be welcome.  I imagine its configuration would be largely similar to the Linux one.

**Comment by licaon-kter** [comment]
Seeing the same on Debian Buster arm64 too, can't actually compile native code since `javah` is no longer provided since Debian Stretch.

**Comment by JonathanLennox** [comment]
@licaon-kter: Can you test whether you can build in Debian Buster if the PR in https://github.com/jitsi/jitsi-srtp/pull/6 is applied?

**Comment by licaon-kter** [comment]
@JonathanLennox Thanks, step by step, https://github.com/jitsi/jitsi-videobridge/issues/1190
